### PR TITLE
Make the ingest service a normal bean

### PR DESCRIPTION
**Pull request by jhunzik**
PR 100 🎉

### CODE REVIEW

**Comment by jhunzik** [comment]
build now

**Comment by emmberk** [comment]
rebased

build now

**Comment by jhunzik** [comment]
Hero'd and confirmed that an ingest service bean is still created.

**Comment by jhunzik** [comment]
build now

**Comment by jhunzik** [comment]
`Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)`
build now

**Pull request merged**
