### PR TITLE
Adds support for a centralized nvd server

### PR DESCRIPTION
**Pull request by oconnormi**
* Removes now unnecessary env vars from pipeline
* Adds additional properties to gradle to allow for pointing at a centralized nvd instance

### CODE REVIEW

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
Forgot to enforce settings on the jenkins side. Trying again, Build Now

**Comment by oconnormi** [comment]
Once more. Build Now

**Comment by oconnormi** [comment]
This is strange, when I run this locally it doesn't do any downloading but for some reason it always does it in CI... Need to investigate more.

**Comment by ahoffer** [comment]
Mike said today that we  still want these changes, but they might need more modification. He is working through a problem with the dependency-check gradle plugin.

**Comment by emmberk** [comment]
I'm closing this for now because we haven't seen the issue in many CI builds. We can reopen if we encounter the issue again.

**Pull request closed without merging**
