### PR TITLE
Improving test logging

### PR DESCRIPTION
**Pull request by Kjames5269**
Moving some stuff around as well as changing the default logger to be prettier.

@emmberk @ahoffer @jhunzik 

Screen Shot 2019-07-31 at 2 55 40 PM

Screen Shot 2019-07-31 at 2 55 58 PM

### CODE REVIEW

**Comment by Kjames5269** [comment]
build now

**Comment by ahoffer** [comment]
@Kjames5269 Does this need a hero?

**Comment by Kjames5269** [comment]
@ahoffer Yeah it does, hero steps are to break any number of test cases and then run a build observing the logs.

**Comment by ahoffer** [comment]
build now

**Comment by ahoffer** [comment]
Heroed. Test logs are much more compact.
image

**Pull request merged**
