### PR TITLE
Improving gradle testing logs

### PR DESCRIPTION
**Pull request by Kjames5269**
Improving gradle testing logs 🎉 

There's a lot of room for improvement but this is what I got that both looks nice and provides a lot of functionality. 

(Also I figured out mid way through writing this that adding --debug or --info to gradle will print out excessive logs so this is the weird middle ground)

@vinamartin @jhunzik

### CODE REVIEW

**Comment by jhunzik** [comment]
I checked it out and the logs look much better. I think you need to run spotless, because it failed for me.

**Comment by Kjames5269** [comment]
build now

**Comment by Kjames5269** [comment]
build now

**Comment by Kjames5269** [comment]
build now
(Jenkins job died)

**Comment by Kjames5269** [comment]
Passed full build locally, overriding CI

**Pull request merged**
