### PR TITLE
Use a consistent Solr version for deployment and itests

### PR DESCRIPTION
**Pull request by jhunzik**

### CODE REVIEW

**Comment by jhunzik** [comment]
build now

**Comment by ahoffer** [comment]
`Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)`
There is a demon slayer stalking the Jenkins servers.

build now

**Comment by jhunzik** [comment]
build now

**Comment by jhunzik** [comment]
build now

**Comment by jhunzik** [comment]
build now

**Comment by jhunzik** [comment]
Hero'd locally and overriding due to known flaky CI results.

**Pull request merged**
