### PR TITLE
Add support for nvd mirror. Enforce mirror in Jenkinsfile

### PR DESCRIPTION
**Pull request by oconnormi**

### CODE REVIEW

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
trying again: Build Now

**Comment by oconnormi** [comment]
Spotless failed: Build Now

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
trying again: build now

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
Hmm not sure why this still fails when using the mirror...
Build Now

**Comment by ahoffer** [comment]
> Hmm not sure why this still fails when using the mirror...
> Build Now

The message wasn't very helpful:
```
[2019-06-06T18:02:47.372Z] * What went wrong:

[2019-06-06T18:02:47.372Z] Execution failed for task ':dependencyCheckAnalyze'.

[2019-06-06T18:02:47.372Z] > java.lang.NullPointerException (no error message)
```

**Comment by oconnormi** [comment]
I _think_ this fixed it, certainly didn't break it more at any rate. Probably good to merge and see if things improve on master

**Pull request merged**
