### PR TITLE
Re-enabling Itests

### PR DESCRIPTION
**Pull request by oconnormi**
Re-enable Itests

### CODE REVIEW

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
Build

**Comment by oconnormi** [comment]
Build Now :man_facepalming:

**Comment by oconnormi** [comment]
Hey can I get a build now?

**Comment by oconnormi** [comment]
Build now please :pray:

**Comment by oconnormi** [comment]
Build Now

**Comment by Kjames5269** [comment]
build now

**Comment by Kjames5269** [comment]
Failed on Owasp download. Full build passed :tada:

**Comment by Kjames5269** [comment]
It looks like it's still skipping Itests though which is weird

**Comment by emmberk** [comment]
The itests did succeed on an earlier CI build for this PR: https://jenkins.phx.connexta.com/service/jenkins/job/ION/job/Multi-Int%20Store/job/PR-53/2/console.
```bash
13:06:08  20:06:05.535 [Test worker] INFO 🐳 [solr:8] - Container solr:8 started
```

**Comment by emmberk** [comment]
build now

**Comment by emmberk** [comment]
rebased

build now

**Comment by emmberk** [comment]
The itests weren't executed, again.

**Comment by Kjames5269** [comment]
build now

**Comment by emmberk** [comment]
There is a permissions issue causing the jenkinsfile changes to be ignored. I'm overriding the build check because there was a successful CI build: https://github.com/connexta/multi-int-store/pull/53#issuecomment-503621649.

**Pull request merged**
